### ISSUE TITLE
One of the in parameters url or valueset or context must be provided

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#124]
Request:

```json
{
    "resourceType": "Parameters",
    "parameter": [
    	{
    		"name": "subjectResource",
    		"valueCode": "Patient"
    	},
        {
            "name": "aggregation",
            "part": [
                {
                    "name": "label",
                    "valueString": "Number of patients"
                },
                {
                    "name": "expression",
                    "valueString": "count()"
                }
            ]
        },
        {
            "name": "grouping",
            "part": [
                {
                    "name": "label",
                    "valueString": "Prescribed TNF inhibitor?"
                },
                {
                    "name": "expression",
                    "valueString": "reverseResolve(MedicationRequest.subject).medicationCodeableConcept.memberOf('http://snomed.info/sct?fhir_vs=ecl/(<< 416897008|Tumour necrosis factor alpha inhibitor product| OR 408154002|Adalimumab 40mg injection solution 0.8mL prefilled syringe|)') contains true"
                }
            ]
        },
        {
            "name": "grouping",
            "part": [
                {
                    "name": "label",
                    "valueString": "Contracted lung infection?"
                },
                {
                    "name": "expression",
                    "valueString": "reverseResolve(Condition.subject).code.memberOf('http://snomed.info/sct?fhir_vs=ecl/(< 64572001|Disease (disorder)| : (363698007|Finding site| = << 39607008|Lung structure|, 370135005|Pathological process| = << 441862004|Infectious process|))') contains true"
                }
            ]
        },
        {
            "name": "filter",
            "valueString": "reverseResolve(Condition.subject).code.memberOf('http://snomed.info/sct?fhir_vs=ecl/(< 64572001|Disease (disorder)| : (363698007|Finding site| = << 39352004|Joint structure|, 370135005|Pathological process| = << 263680009|Autoimmune process|))') contains true"
        },
        {
            "name": "filter",
            "valueString": "reverseResolve(Condition.subject).code.memberOf('http://snomed.info/sct?fhir_vs=ecl/(< 64572001|Disease (disorder)| : (363698007|Finding site| = << 39607008|Lung structure|, 263502005|Clinical course| = << 90734009|Chronic|))') contains true"
        }
    ]
}
```

Exception:

```
17:20:37.131 [Executor task launch worker for task 142] [qiRuCCxHaoHHmszO] ERROR org.apache.spark.executor.Executor - Exception in task 1.0 in stage 274.0 (TID 142)
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 : One of the in parameters url or valueset or context must be provided
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:302)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:219)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:215)
	at ca.uhn.fhir.rest.client.impl.ClientInvocationHandler.invoke(ClientInvocationHandler.java:62)
	at com.sun.proxy.$Proxy90.expand(Unknown Source)
	at au.csiro.pathling.fhirpath.function.memberof.MemberOfMapper.call(MemberOfMapper.java:156)
	at org.apache.spark.sql.Dataset.$anonfun$mapPartitions$1(Dataset.scala:2793)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:195)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:20:37.131 [Executor task launch worker for task 141] [qiRuCCxHaoHHmszO] ERROR org.apache.spark.executor.Executor - Exception in task 0.0 in stage 274.0 (TID 141)
ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 : One of the in parameters url or valueset or context must be provided
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:302)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:219)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:215)
	at ca.uhn.fhir.rest.client.impl.ClientInvocationHandler.invoke(ClientInvocationHandler.java:62)
	at com.sun.proxy.$Proxy90.expand(Unknown Source)
	at au.csiro.pathling.fhirpath.function.memberof.MemberOfMapper.call(MemberOfMapper.java:156)
	at org.apache.spark.sql.Dataset.$anonfun$mapPartitions$1(Dataset.scala:2793)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:195)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:20:37.158 [task-result-getter-1] [] WARN  o.a.spark.scheduler.TaskSetManager - Lost task 1.0 in stage 274.0 (TID 142, rbh-wireless-169-87.pool.csiro.au, executor driver): ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 : One of the in parameters url or valueset or context must be provided
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:302)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:219)
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:215)
	at ca.uhn.fhir.rest.client.impl.ClientInvocationHandler.invoke(ClientInvocationHandler.java:62)
	at com.sun.proxy.$Proxy90.expand(Unknown Source)
	at au.csiro.pathling.fhirpath.function.memberof.MemberOfMapper.call(MemberOfMapper.java:156)
	at org.apache.spark.sql.Dataset.$anonfun$mapPartitions$1(Dataset.scala:2793)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:195)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by johngrimes** [comment]
Looks like requests are being made with an empty `valueSet` parameter:

```
17:24:50.315 [Executor task launch worker for task 37] [FUunFvEldi5Cut1t] INFO  a.c.p.f.f.memberof.MemberOfMapper - Client request body:
{"resourceType":"Parameters","parameter":[{"name":"valueSet"},{"name":"count","valueInteger":14}]}
```
