### ISSUE TITLE
ResourceNotFoundError results in 500

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#226]
A request for a resource which is not available results in a 500 Internal Server Error:

```
04:46:41.624 [http-nio-8080-exec-4] [04BwnnZcbRnA8FwJ] ERROR c.u.f.r.s.i.ExceptionHandlingInterceptor - Failure during REST processing
ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Unexpected error occurred
	at au.csiro.pathling.fhir.ErrorHandlingInterceptor.internalServerError(ErrorHandlingInterceptor.java:137)
	at au.csiro.pathling.fhir.ErrorHandlingInterceptor.doConvertError(ErrorHandlingInterceptor.java:110)
	at au.csiro.pathling.fhir.ErrorHandlingInterceptor.doConvertError(ErrorHandlingInterceptor.java:77)
	at au.csiro.pathling.fhir.ErrorHandlingInterceptor.doConvertError(ErrorHandlingInterceptor.java:77)
	at au.csiro.pathling.fhir.ErrorHandlingInterceptor.doConvertError(ErrorHandlingInterceptor.java:77)
	at au.csiro.pathling.fhir.ErrorHandlingInterceptor.convertError(ErrorHandlingInterceptor.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at ca.uhn.fhir.interceptor.executor.InterceptorService$HookInvoker.invoke(InterceptorService.java:514)
	at ca.uhn.fhir.interceptor.executor.InterceptorService.doCallHooks(InterceptorService.java:288)
	at ca.uhn.fhir.interceptor.executor.InterceptorService.callHooksAndReturnObject(InterceptorService.java:257)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1093)
	at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:367)
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1743)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: au.csiro.pathling.errors.ResourceNotFoundError: Requested resource type not available within selected database: Patient
	at au.csiro.pathling.io.ResourceReader.read(ResourceReader.java:181)
	at au.csiro.pathling.fhirpath.ResourcePath.build(ResourcePath.java:97)
	at au.csiro.pathling.fhirpath.ResourcePath.build(ResourcePath.java:71)
	at au.csiro.pathling.aggregate.FreshAggregateExecutor.execute(FreshAggregateExecutor.java:77)
	at au.csiro.pathling.aggregate.CachingAggregateExecutor$1.load(CachingAggregateExecutor.java:69)
	at au.csiro.pathling.aggregate.CachingAggregateExecutor$1.load(CachingAggregateExecutor.java:66)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at au.csiro.pathling.aggregate.CachingAggregateExecutor.execute(CachingAggregateExecutor.java:80)
	at au.csiro.pathling.aggregate.AggregateProvider.aggregate(AggregateProvider.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:245)
	at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:329)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:268)
	at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:375)
	at ca.uhn.fhir.rest.server.method.OperationMethodBinding.invokeServer(OperationMethodBinding.java:304)
	at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1052)
	... 36 common frames omitted
Caused by: au.csiro.pathling.errors.ResourceNotFoundError: Requested resource type not available within selected database: Patient
	at au.csiro.pathling.io.ResourceReader.getDatasetForResourceType(ResourceReader.java:191)
	at au.csiro.pathling.io.ResourceReader$1.load(ResourceReader.java:89)
	at au.csiro.pathling.io.ResourceReader$1.load(ResourceReader.java:86)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at au.csiro.pathling.io.ResourceReader.read(ResourceReader.java:179)
	... 61 common frames omitted
```

This should return a 404 with the error detail: `Requested resource type not available within selected database: Patient`.

**Comment by johngrimes** [comment]
Fixed by c4b1726.
