### ISSUE TITLE
Expression with where and comparison operator causes AnalysisError

### ISSUE THREAD

**Issue by johngrimes** [aehrc/pathling#60]
Here is the expression:

```
@2018-05-06 > reverseResolve(MedicationRequest.subject).where(
$this.medicationCodeableConcept.coding contains http://snomed.info/sct|407317001
).first().authoredOn
```

And here is the error:

```
Caused by: org.apache.spark.sql.AnalysisException: Resolved attribute(s) d736d2f#17162 missing from id#16716,resource#16762,01122a9#16793,(to_date('2018-05-06') > to_date(`d736d2f`))#17197,01122a9_id#16789,d736d2f_id#17156 in operator !Aggregate [(to_date(2018-05-06, None) > to_date(d736d2f#17162, None))], [(to_date(2018-05-06, None) > to_date(d736d2f#17162, None)) AS (to_date('2018-05-06') > to_date(`d736d2f`))#17227, count(01122a9#16793) AS count(01122a9)#17228L].;;
!Aggregate [(to_date(2018-05-06, None) > to_date(d736d2f#17162, None))], [(to_date(2018-05-06, None) > to_date(d736d2f#17162, None)) AS (to_date('2018-05-06') > to_date(`d736d2f`))#17227, count(01122a9#16793) AS count(01122a9)#17228L]
+- Join Inner, (01122a9_id#16789 = d736d2f_id#17156)
   :- Project [id#16716, resource#16762, 01122a9_id#16789, resource#16762 AS 01122a9#16793]
   :  +- Project [id#16716, resource#16762, id#16716 AS 01122a9_id#16789]
   :     +- Project [id#16716, resource#16762]
   :        +- Project [id#16716, meta#16717, implicitRules#16718, language#16719, text#16720, identifier#16721, active#16722, name#16723, telecom#16724, gender#16725, birthDate#16726, deceasedBoolean#16727, deceasedDateTime#16728, address#16729, maritalStatus#16730, multipleBirthInteger#16731, multipleBirthBoolean#16732, photo#16733, contact#16734, communication#16735, generalPractitioner#16736, managingOrganization#16737, link#16738, named_struct(id, id#16716, meta, meta#16717, implicitRules, implicitRules#16718, language, language#16719, text, text#16720, identifier, identifier#16721, active, active#16722, name, name#16723, telecom, telecom#16724, gender, gender#16725, birthDate, birthDate#16726, deceasedBoolean, deceasedBoolean#16727, ... 22 more fields) AS resource#16762]
   :           +- Relation[id#16716,meta#16717,implicitRules#16718,language#16719,text#16720,identifier#16721,active#16722,name#16723,telecom#16724,gender#16725,birthDate#16726,deceasedBoolean#16727,deceasedDateTime#16728,address#16729,maritalStatus#16730,multipleBirthInteger#16731,multipleBirthBoolean#16732,photo#16733,contact#16734,communication#16735,generalPractitioner#16736,managingOrganization#16737,link#16738] parquet
   +- Deduplicate [d736d2f_id#17156, (to_date('2018-05-06') > to_date(`d736d2f`))#17197]
      +- Project [d736d2f_id#17156, (to_date(2018-05-06, None) > to_date(d736d2f#17162, None)) AS (to_date('2018-05-06') > to_date(`d736d2f`))#17197]
         +- Project [3a83148_id#17121, first(3a83148, true)#17144, 792a80a_id#17147, 792a80a#17151, d736d2f_id#17156, d736d2f#17162, (to_date(2018-05-06, None) > to_date(d736d2f#17162, None)) AS comparisonResult#17169]
            +- Project [3a83148_id#17121, first(3a83148, true)#17144, 792a80a_id#17147, 792a80a#17151, d736d2f_id#17156, 792a80a#17151.authoredOn AS d736d2f#17162]
               +- Project [3a83148_id#17121, first(3a83148, true)#17144, 792a80a_id#17147, 792a80a#17151, 792a80a_id#17147 AS d736d2f_id#17156]
                  +- Project [3a83148_id#17121, first(3a83148, true)#17144, 792a80a_id#17147, first(3a83148, true)#17144 AS 792a80a#17151]
                     +- Project [3a83148_id#17121, first(3a83148, true)#17144, 3a83148_id#17121 AS 792a80a_id#17147]
                        +- Aggregate [3a83148_id#17121], [3a83148_id#17121, first(3a83148#17128, true) AS first(3a83148, true)#17144]
                           +- Project [ac0ad56#16976, 7099464_id#17031, max(equality)#17106, f7524ee_id#17110, f7524ee#17115, 3a83148_id#17121, ac0ad56#16976 AS 3a83148#17128]
                              +- Project [ac0ad56#16976, 7099464_id#17031, max(equality)#17106, f7524ee_id#17110, f7524ee#17115, f7524ee_id#17110 AS 3a83148_id#17121]
                                 +- Filter (f7524ee#17115 = true)
                                    +- Project [ac0ad56#16976, 7099464_id#17031, max(equality)#17106, f7524ee_id#17110, max(equality)#17106 AS f7524ee#17115]
                                       +- Project [ac0ad56#16976, 7099464_id#17031, max(equality)#17106, 7099464_id#17031 AS f7524ee_id#17110]
                                          +- Aggregate [ac0ad56#16976, 7099464_id#17031], [ac0ad56#16976, 7099464_id#17031, max(equality#17070) AS max(equality)#17106]
                                             +- Project [id#16716, resource#16762, 01122a9_id#16789, 01122a9#16793, id#16798, 2071abb#16923, 2071abb_id#16919, b5e3374_id#16927, b5e3374#16932, ac0ad56_id#16965, ac0ad56#16976, 28667b4_id#16988, 28667b4#17001, explodeResult#17016, 7099464_id#17031, 7099464#17047, CASE WHEN isnull(named_struct(id, null, system, http://snomed.info/sct, version, null, code, 407317001, display, null, userSelected, false)) THEN cast(null as boolean) WHEN isnull(7099464#17047) THEN false ELSE CASE WHEN (((isnull(7099464#17047.system) || isnull(7099464#17047.code)) || isnull(named_struct(id, null, system, http://snomed.info/sct, version, null, code, 407317001, display, null, userSelected, false).system)) || isnull(named_struct(id, null, system, http://snomed.info/sct, version, null, code, 407317001, display, null, userSelected, false).code)) THEN cast(null as boolean) WHEN (isnull(7099464#17047.version) || isnull(named_struct(id, null, system, http://snomed.info/sct, version, null, code, 407317001, display, null, userSelected, false).version)) THEN ((7099464#17047.system = named_struct(id, null, system, http://snomed.info/sct, version, null, code, 407317001, display, null, userSelected, false).system) && (7099464#17047.code = named_struct(id, null, system, http://snomed.info/sct, version, null, code, 407317001, display, null, userSelected, false).code)) ELSE (((7099464#17047.system = named_struct(id, null, system, http://snomed.info/sct, version, null, code, 407317001, display, null, userSelected, false).system) && (7099464#17047.code = named_struct(id, null, system, http://snomed.info/sct, version, null, code, 407317001, display, null, userSelected, false).code)) && (7099464#17047.version = null)) END END AS equality#17070]
                                                +- Project [id#16716, resource#16762, 01122a9_id#16789, 01122a9#16793, id#16798, 2071abb#16923, 2071abb_id#16919, b5e3374_id#16927, b5e3374#16932, ac0ad56_id#16965, ac0ad56#16976, 28667b4_id#16988, 28667b4#17001, explodeResult#17016, 7099464_id#17031, explodeResult#17016 AS 7099464#17047]
                                                   +- Project [id#16716, resource#16762, 01122a9_id#16789, 01122a9#16793, id#16798, 2071abb#16923, 2071abb_id#16919, b5e3374_id#16927, b5e3374#16932, ac0ad56_id#16965, ac0ad56#16976, 28667b4_id#16988, 28667b4#17001, explodeResult#17016, 28667b4_id#16988 AS 7099464_id#17031]
                                                      +- Project [id#16716, resource#16762, 01122a9_id#16789, 01122a9#16793, id#16798, 2071abb#16923, 2071abb_id#16919, b5e3374_id#16927, b5e3374#16932, ac0ad56_id#16965, ac0ad56#16976, 28667b4_id#16988, 28667b4#17001, explodeResult#17016]
                                                         +- Generate explode(28667b4#17001.coding), true, [explodeResult#17016]
                                                            +- Project [id#16716, resource#16762, 01122a9_id#16789, 01122a9#16793, id#16798, 2071abb#16923, 2071abb_id#16919, b5e3374_id#16927, b5e3374#16932, ac0ad56_id#16965, ac0ad56#16976, 28667b4_id#16988, ac0ad56#16976.medicationCodeableConcept AS 28667b4#17001]
                                                               +- Project [id#16716, resource#16762, 01122a9_id#16789, 01122a9#16793, id#16798, 2071abb#16923, 2071abb_id#16919, b5e3374_id#16927, b5e3374#16932, ac0ad56_id#16965, ac0ad56#16976, ac0ad56_id#16965 AS 28667b4_id#16988]
                                                                  +- Project [id#16716, resource#16762, 01122a9_id#16789, 01122a9#16793, id#16798, 2071abb#16923, 2071abb_id#16919, b5e3374_id#16927, b5e3374#16932, ac0ad56_id#16965, 2071abb#16923 AS ac0ad56#16976]
                                                                     +- Project [id#16716, resource#16762, 01122a9_id#16789, 01122a9#16793, id#16798, 2071abb#16923, 2071abb_id#16919, b5e3374_id#16927, b5e3374#16932, 01122a9_id#16789 AS ac0ad56_id#16965]
                                                                        +- Join LeftOuter, (01122a9_id#16789 = b5e3374#16932.reference)
                                                                           :- Project [id#16716, resource#16762, 01122a9_id#16789, resource#16762 AS 01122a9#16793]
                                                                           :  +- Project [id#16716, resource#16762, id#16716 AS 01122a9_id#16789]
                                                                           :     +- Project [id#16716, resource#16762]
                                                                           :        +- Project [id#16716, meta#16717, implicitRules#16718, language#16719, text#16720, identifier#16721, active#16722, name#16723, telecom#16724, gender#16725, birthDate#16726, deceasedBoolean#16727, deceasedDateTime#16728, address#16729, maritalStatus#16730, multipleBirthInteger#16731, multipleBirthBoolean#16732, photo#16733, contact#16734, communication#16735, generalPractitioner#16736, managingOrganization#16737, link#16738, named_struct(id, id#16716, meta, meta#16717, implicitRules, implicitRules#16718, language, language#16719, text, text#16720, identifier, identifier#16721, active, active#16722, name, name#16723, telecom, telecom#16724, gender, gender#16725, birthDate, birthDate#16726, deceasedBoolean, deceasedBoolean#16727, ... 22 more fields) AS resource#16762]
                                                                           :           +- Relation[id#16716,meta#16717,implicitRules#16718,language#16719,text#16720,identifier#16721,active#16722,name#16723,telecom#16724,gender#16725,birthDate#16726,deceasedBoolean#16727,deceasedDateTime#16728,address#16729,maritalStatus#16730,multipleBirthInteger#16731,multipleBirthBoolean#16732,photo#16733,contact#16734,communication#16735,generalPractitioner#16736,managingOrganization#16737,link#16738] parquet
                                                                           +- Project [id#16798, 2071abb#16923, 2071abb_id#16919, b5e3374_id#16927, 2071abb#16923.subject AS b5e3374#16932]
                                                                              +- Project [id#16798, 2071abb#16923, 2071abb_id#16919, 2071abb_id#16919 AS b5e3374_id#16927]
                                                                                 +- Project [id#16798, 2071abb#16876 AS 2071abb#16923, 2071abb_id#16919]
                                                                                    +- Project [id#16798, 2071abb#16876, id#16798 AS 2071abb_id#16919]
                                                                                       +- Project [id#16798, 2071abb#16876]
                                                                                          +- Project [id#16798, meta#16799, implicitRules#16800, language#16801, text#16802, identifier#16803, status#16804, statusReason#16805, intent#16806, category#16807, priority#16808, doNotPerform#16809, reportedBoolean#16810, reportedReference#16811, medicationCodeableConcept#16812, medicationReference#16813, subject#16814, encounter#16815, supportingInformation#16816, authoredOn#16817, requester#16818, performer#16819, performerType#16820, recorder#16821, ... 16 more fields]
                                                                                             +- Relation[id#16798,meta#16799,implicitRules#16800,language#16801,text#16802,identifier#16803,status#16804,statusReason#16805,intent#16806,category#16807,priority#16808,doNotPerform#16809,reportedBoolean#16810,reportedReference#16811,medicationCodeableConcept#16812,medicationReference#16813,subject#16814,encounter#16815,supportingInformation#16816,authoredOn#16817,requester#16818,performer#16819,performerType#16820,recorder#16821,... 15 more fields] parquet

	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.failAnalysis(CheckAnalysis.scala:43)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.failAnalysis(Analyzer.scala:95)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:369)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:86)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:86)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:95)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$executeAndCheck$1.apply(Analyzer.scala:108)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$executeAndCheck$1.apply(Analyzer.scala:105)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:201)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:105)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:58)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:56)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:48)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:78)
	at org.apache.spark.sql.RelationalGroupedDataset.toDF(RelationalGroupedDataset.scala:65)
	at org.apache.spark.sql.RelationalGroupedDataset.agg(RelationalGroupedDataset.scala:224)
	at org.apache.spark.sql.RelationalGroupedDataset.agg(RelationalGroupedDataset.scala:223)
	at au.csiro.pathling.query.AggregateExecutor.execute(AggregateExecutor.java:120)
	... 31 common frames omitted
```

**Comment by johngrimes** [comment]
@piotrszul Would you mind taking a look at this one?
